---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go mod tidy
      - go build -ldflags "-X main.Version=${DRONE_TAG}" -o admspublic
    environment:
      GOARCH: arm64
      GOOS: linux
      CGO_ENABLED: 0
      GOPRIVATE: "*.solutions.im"

  - name: docker
    image: plugins/docker
    tag: [linux-arm64]
    environment:
      PLUGIN_MTU: 1300
    settings:
      dockerfile: Dockerfile
      repo: registry.solutions.im/admspublic
      registry: registry.solutions.im
      auto_tag: true
      auto_tag_suffix: linux-arm64

volumes:
  - name: deps
    temp: {}

trigger:
  event:
    - tag
    - release

---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go mod tidy
      - go build -ldflags "-X main.Version=${DRONE_TAG}" -o admspublic
    environment:
      GOARCH: amd64
      GOOS: linux
      CGO_ENABLED: 0
      GOPRIVATE: "*.solutions.im"

  - name: docker
    image: plugins/docker
    tag: [linux-amd64]
    environment:
      PLUGIN_MTU: 1300
    settings:
      dockerfile: Dockerfile
      repo: registry.solutions.im/admspublic
      registry: registry.solutions.im
      auto_tag: true
      auto_tag_suffix: linux-amd64

volumes:
  - name: deps
    temp: {}

trigger:
  event:
    - tag
    - release

---
kind: pipeline
name: manifest_and_deployment

steps:
  - name: manifest
    image: plugins/manifest
    settings:
      target: registry.solutions.im/admspublic
      spec: manifest.tmpl
      auto_tag: true
      platforms:
        - linux/amd64
        - linux/arm64

  - name: send
    image: plugins/webhook
    settings:
      urls: https://chat.solutions.im/hooks/u7dufgd17tro8nqxg97akey3ky
      content_type: application/json
      template: |
        {
          "text": "{{ repo.name }} {{ build.tag }} build finished with {{ build.status }}.\nCommit message : {{ commit.message }}"
        }

#  - name : deploy
#    image: quay.io/honestbee/drone-kubernetes
#    kubernetes_server: https://kubernetes.company.org
#      namespace: admspublic
#      deployment: web
#      repo: registry.solutions.im/admspublic
#      container: web
#      tag: latest

trigger:
  event:
    - tag
    - release

depends_on:
  - arm64
  - amd64
