--@block
drop TABLE aggregates;
--@block
delete from aggregates;
--@block
select geocode
from aggregates;
--@block
copy aggregates
from '/46.csv' delimiter ';' csv header;
--@block
select edu,
    edu1 as NoEducation,
    edu2 as Class1,
    edu3 as Class2,
    edu3 as Class3,
    edu4 as Class4,
    edu5 as Class5,
    edu6 as Class6,
    edu7 as Class7,
    edu8 as Class8,
    edu9 as Class9,
    edu10 as SCC,
    edu12 as HSC,
    edu15 as BachelorEquivalent,
    edu18 as MastersEquivalentOrHigher,
    (
        edu1 + edu2 + edu3 + edu4 + edu5 + edu6 + edu7 + edu8 + edu9 + edu10 + edu12 + edu15 + edu18
    ) as Total
from agregateds;
-- @block test
select sum(occ) as occ,
    sum(occ2) as occ2,
    sum(occ3) as occ3,
    sum(occ4) as occ4,
    sum(occ5) as occ5,
    (
        sum(occ) + sum(occ2) + sum(occ3) + sum(occ4) + sum(occ5)
    ) as total
from agregateds
where subpath(geocode, 0, %d) = ?;
--@block test2
select edu,
    edu1,
    edu2,
    edu3,
    edu4,
    edu5,
    edu6,
    edu7,
    edu8,
    edu9,
    edu10,
    edu12,
    edu15,
    edu18,
    (
        edu1 + edu2 + edu3 + edu4 + edu5 + edu6 + edu7 + edu8 + edu9 + edu10 + edu12 + edu15 + edu18
    ) as total
from agregateds;
--@block
select edu,
    edu1,
    edu2
from agregateds;
--@block
select edu,
    edu1 as NoEducation,
    edu2 as Class1,
    edu3 as Class2,
    edu3 as Class3,
    edu4 as Class4,
    edu5 as Class5,
    edu6 as Class6,
    edu7 as Class7,
    edu8 as Class8,
    edu9 as Class9,
    edu10 as SCC,
    edu12 as HSC,
    edu15 as BachelorEquivalent,
    edu18 as MastersEquivalentOrHigher,
    (
        edu1 + edu2 + edu3 + edu4 + edu5 + edu6 + edu7 + edu8 + edu9 + edu10 + edu12 + edu15 + edu18
    ) as Total
from agregateds;
--@block
select sum(sex) as male,
    sum(sex2) as female,
    sum(sex3) as hijra,
    (sum(sex) + sum(sex2) + sum(sex3)) as total
from agregateds;
--@block
SELECT sum(hh_f) as Number_Of_Fishery_Household,
    (sum(hh_f) / sum(hh_sno)) * 100 as Percentage
from agregateds
where hh_f = 1;
--@block
COPY agregateds
FROM '/46.csv' DELIMITER ';' CSV HEADER;
--@block
alter table agregateds
alter COLUMN t101 TYPE NUMERIC USING t101::NUMERIC,
    alter COLUMN t102 TYPE NUMERIC USING t102::NUMERIC,
    alter COLUMN t103 TYPE NUMERIC USING t103::NUMERIC,
    alter COLUMN t104 TYPE NUMERIC USING t104::NUMERIC,
    alter COLUMN t105 TYPE NUMERIC USING t105::NUMERIC,
    alter COLUMN t112 TYPE NUMERIC USING t112::NUMERIC,
    alter COLUMN t113 TYPE NUMERIC USING t113::NUMERIC,
    alter COLUMN t114 TYPE NUMERIC USING t114::NUMERIC,
    alter COLUMN t121 TYPE NUMERIC USING t121::NUMERIC,
    alter COLUMN t122 TYPE NUMERIC USING t122::NUMERIC,
    alter COLUMN t123 TYPE NUMERIC USING t123::NUMERIC,
    alter COLUMN t124 TYPE NUMERIC USING t124::NUMERIC,
    alter COLUMN t125 TYPE NUMERIC USING t125::NUMERIC,
    alter COLUMN t127 TYPE NUMERIC USING t127::NUMERIC,
    alter COLUMN t128 TYPE NUMERIC USING t128::NUMERIC,
    alter COLUMN t129 TYPE NUMERIC USING t129::NUMERIC,
    alter COLUMN t130 TYPE NUMERIC USING t130::NUMERIC,
    alter COLUMN t131 TYPE NUMERIC USING t131::NUMERIC,
    alter COLUMN t132 TYPE NUMERIC USING t132::NUMERIC,
    alter COLUMN t134 TYPE NUMERIC USING t134::NUMERIC,
    alter COLUMN t135 TYPE NUMERIC USING t135::NUMERIC,
    alter COLUMN t157 TYPE NUMERIC USING t157::NUMERIC,
    alter COLUMN t158 TYPE NUMERIC USING t158::NUMERIC,
    alter COLUMN t159 TYPE NUMERIC USING t159::NUMERIC,
    alter COLUMN t160 TYPE NUMERIC USING t160::NUMERIC,
    alter COLUMN t161 TYPE NUMERIC USING t161::NUMERIC,
    alter COLUMN t167 TYPE NUMERIC USING t167::NUMERIC,
    alter COLUMN t169 TYPE NUMERIC USING t169::NUMERIC,
    alter COLUMN t175 TYPE NUMERIC USING t175::NUMERIC,
    alter COLUMN t176 TYPE NUMERIC USING t176::NUMERIC,
    alter COLUMN t177 TYPE NUMERIC USING t177::NUMERIC,
    alter COLUMN t179 TYPE NUMERIC USING t179::NUMERIC,
    alter COLUMN t182 TYPE NUMERIC USING t182::NUMERIC,
    alter COLUMN t185 TYPE NUMERIC USING t185::NUMERIC,
    alter COLUMN t106 TYPE NUMERIC USING t106::NUMERIC,
    alter COLUMN t107 TYPE NUMERIC USING t107::NUMERIC,
    alter COLUMN t108 TYPE NUMERIC USING t108::NUMERIC,
    alter COLUMN t109 TYPE NUMERIC USING t109::NUMERIC,
    alter COLUMN t110 TYPE NUMERIC USING t110::NUMERIC,
    alter COLUMN t111 TYPE NUMERIC USING t111::NUMERIC,
    alter COLUMN t115 TYPE NUMERIC USING t115::NUMERIC,
    alter COLUMN t116 TYPE NUMERIC USING t116::NUMERIC,
    alter COLUMN t117 TYPE NUMERIC USING t117::NUMERIC,
    alter COLUMN t118 TYPE NUMERIC USING t118::NUMERIC,
    alter COLUMN t119 TYPE NUMERIC USING t119::NUMERIC,
    alter COLUMN t120 TYPE NUMERIC USING t120::NUMERIC,
    alter COLUMN t126 TYPE NUMERIC USING t126::NUMERIC,
    alter COLUMN t133 TYPE NUMERIC USING t133::NUMERIC,
    alter COLUMN t136 TYPE NUMERIC USING t136::NUMERIC,
    alter COLUMN t137 TYPE NUMERIC USING t137::NUMERIC,
    alter COLUMN t138 TYPE NUMERIC USING t138::NUMERIC,
    alter COLUMN t139 TYPE NUMERIC USING t139::NUMERIC,
    alter COLUMN t140 TYPE NUMERIC USING t140::NUMERIC,
    alter COLUMN t141 TYPE NUMERIC USING t141::NUMERIC,
    alter COLUMN t142 TYPE NUMERIC USING t142::NUMERIC,
    alter COLUMN t143 TYPE NUMERIC USING t143::NUMERIC,
    alter COLUMN t144 TYPE NUMERIC USING t144::NUMERIC,
    alter COLUMN t145 TYPE NUMERIC USING t145::NUMERIC,
    alter COLUMN t146 TYPE NUMERIC USING t146::NUMERIC,
    alter COLUMN t147 TYPE NUMERIC USING t147::NUMERIC,
    alter COLUMN t148 TYPE NUMERIC USING t148::NUMERIC,
    alter COLUMN t149 TYPE NUMERIC USING t149::NUMERIC,
    alter COLUMN t150 TYPE NUMERIC USING t150::NUMERIC,
    alter COLUMN t151 TYPE NUMERIC USING t151::NUMERIC,
    alter COLUMN t152 TYPE NUMERIC USING t152::NUMERIC,
    alter COLUMN t153 TYPE NUMERIC USING t153::NUMERIC,
    alter COLUMN t154 TYPE NUMERIC USING t154::NUMERIC,
    alter COLUMN t155 TYPE NUMERIC USING t155::NUMERIC,
    alter COLUMN t156 TYPE NUMERIC USING t156::NUMERIC,
    alter COLUMN t162 TYPE NUMERIC USING t162::NUMERIC,
    alter COLUMN t163 TYPE NUMERIC USING t163::NUMERIC,
    alter COLUMN t164 TYPE NUMERIC USING t164::NUMERIC,
    alter COLUMN t165 TYPE NUMERIC USING t165::NUMERIC,
    alter COLUMN t166 TYPE NUMERIC USING t166::NUMERIC,
    alter COLUMN t168 TYPE NUMERIC USING t168::NUMERIC,
    alter COLUMN t170 TYPE NUMERIC USING t170::NUMERIC,
    alter COLUMN t171 TYPE NUMERIC USING t171::NUMERIC,
    alter COLUMN t172 TYPE NUMERIC USING t172::NUMERIC,
    alter COLUMN t173 TYPE NUMERIC USING t173::NUMERIC,
    alter COLUMN t174 TYPE NUMERIC USING t174::NUMERIC,
    alter COLUMN t178 TYPE NUMERIC USING t178::NUMERIC,
    alter COLUMN t180 TYPE NUMERIC USING t180::NUMERIC,
    alter COLUMN t181 TYPE NUMERIC USING t181::NUMERIC,
    alter COLUMN t183 TYPE NUMERIC USING t183::NUMERIC,
    alter COLUMN t184 TYPE NUMERIC USING t184::NUMERIC,
    alter COLUMN t186 TYPE NUMERIC USING t186::NUMERIC,
    alter COLUMN t187 TYPE NUMERIC USING t187::NUMERIC,
    alter COLUMN t188 TYPE NUMERIC USING t188::NUMERIC,
    alter COLUMN t189 TYPE NUMERIC USING t189::NUMERIC,
    alter COLUMN t190 TYPE NUMERIC USING t190::NUMERIC,
    alter COLUMN t191 TYPE NUMERIC USING t191::NUMERIC,
    alter COLUMN t192 TYPE NUMERIC USING t192::NUMERIC,
    alter COLUMN t193 TYPE NUMERIC USING t193::NUMERIC,
    alter COLUMN t194 TYPE NUMERIC USING t194::NUMERIC,
    alter COLUMN t195 TYPE NUMERIC USING t195::NUMERIC,
    alter COLUMN t196 TYPE NUMERIC USING t196::NUMERIC,
    alter COLUMN t197 TYPE NUMERIC USING t197::NUMERIC,
    alter COLUMN t198 TYPE NUMERIC USING t198::NUMERIC,
    alter COLUMN t199 TYPE NUMERIC USING t199::NUMERIC,
    alter COLUMN t200 TYPE NUMERIC USING t200::NUMERIC,
    alter COLUMN t201 TYPE NUMERIC USING t201::NUMERIC,
    alter COLUMN t202 TYPE NUMERIC USING t202::NUMERIC,
    alter COLUMN t203 TYPE NUMERIC USING t203::NUMERIC;
--@block 
alter table agregateds
ALTER COLUMN pnl509 TYPE NUMERIC USING pnl509::NUMERIC,
    ALTER COLUMN pnn509 TYPE NUMERIC USING pnn509::NUMERIC,
    ALTER COLUMN pnl513 TYPE NUMERIC USING pnl513::NUMERIC,
    ALTER COLUMN pnn513 TYPE NUMERIC USING pnn513::NUMERIC,
    ALTER COLUMN pnl514 TYPE NUMERIC USING pnl514::NUMERIC,
    ALTER COLUMN pnn514 TYPE NUMERIC USING pnn514::NUMERIC,
    ALTER COLUMN pnl515 TYPE NUMERIC USING pnl515::NUMERIC,
    ALTER COLUMN pnn515 TYPE NUMERIC USING pnn515::NUMERIC,
    ALTER COLUMN pnl516 TYPE NUMERIC USING pnl516::NUMERIC,
    ALTER COLUMN pnn516 TYPE NUMERIC USING pnn516::NUMERIC,
    ALTER COLUMN pnl517 TYPE NUMERIC USING pnl517::NUMERIC,
    ALTER COLUMN pnn517 TYPE NUMERIC USING pnn517::NUMERIC,
    ALTER COLUMN pnl518 TYPE NUMERIC USING pnl518::NUMERIC,
    ALTER COLUMN pnn518 TYPE NUMERIC USING pnn518::NUMERIC,
    ALTER COLUMN pnl519 TYPE NUMERIC USING pnl519::NUMERIC,
    ALTER COLUMN pnn519 TYPE NUMERIC USING pnn519::NUMERIC,
    ALTER COLUMN pnl520 TYPE NUMERIC USING pnl520::NUMERIC,
    ALTER COLUMN pnn520 TYPE NUMERIC USING pnn520::NUMERIC,
    ALTER COLUMN pnl525 TYPE NUMERIC USING pnl525::NUMERIC,
    ALTER COLUMN pnn525 TYPE NUMERIC USING pnn525::NUMERIC,
    ALTER COLUMN pnl526 TYPE NUMERIC USING pnl526::NUMERIC,
    ALTER COLUMN pnn526 TYPE NUMERIC USING pnn526::NUMERIC,
    ALTER COLUMN pnl527 TYPE NUMERIC USING pnl527::NUMERIC,
    ALTER COLUMN pnn527 TYPE NUMERIC USING pnn527::NUMERIC,
    ALTER COLUMN pnl528 TYPE NUMERIC USING pnl528::NUMERIC,
    ALTER COLUMN pnn528 TYPE NUMERIC USING pnn528::NUMERIC,
    ALTER COLUMN pnl529 TYPE NUMERIC USING pnl529::NUMERIC,
    ALTER COLUMN pnn529 TYPE NUMERIC USING pnn529::NUMERIC,
    ALTER COLUMN pnl530 TYPE NUMERIC USING pnl530::NUMERIC,
    ALTER COLUMN pnn530 TYPE NUMERIC USING pnn530::NUMERIC,
    ALTER COLUMN pnl531 TYPE NUMERIC USING pnl531::NUMERIC,
    ALTER COLUMN pnn531 TYPE NUMERIC USING pnn531::NUMERIC,
    ALTER COLUMN pnl532 TYPE NUMERIC USING pnl532::NUMERIC,
    ALTER COLUMN pnn532 TYPE NUMERIC USING pnn532::NUMERIC,
    ALTER COLUMN pnl533 TYPE NUMERIC USING pnl533::NUMERIC,
    ALTER COLUMN pnn533 TYPE NUMERIC USING pnn533::NUMERIC,
    ALTER COLUMN pnl534 TYPE NUMERIC USING pnl534::NUMERIC,
    ALTER COLUMN pnn534 TYPE NUMERIC USING pnn534::NUMERIC,
    ALTER COLUMN pnl535 TYPE NUMERIC USING pnl535::NUMERIC,
    ALTER COLUMN pnn535 TYPE NUMERIC USING pnn535::NUMERIC,
    ALTER COLUMN pnl536 TYPE NUMERIC USING pnl536::NUMERIC,
    ALTER COLUMN pnn536 TYPE NUMERIC USING pnn536::NUMERIC,
    ALTER COLUMN pnl537 TYPE NUMERIC USING pnl537::NUMERIC,
    ALTER COLUMN pnn537 TYPE NUMERIC USING pnn537::NUMERIC,
    ALTER COLUMN pnl540 TYPE NUMERIC USING pnl540::NUMERIC,
    ALTER COLUMN pnn540 TYPE NUMERIC USING pnn540::NUMERIC,
    ALTER COLUMN pnl541 TYPE NUMERIC USING pnl541::NUMERIC,
    ALTER COLUMN pnn541 TYPE NUMERIC USING pnn541::NUMERIC,
    ALTER COLUMN pnl542 TYPE NUMERIC USING pnl542::NUMERIC,
    ALTER COLUMN pnn542 TYPE NUMERIC USING pnn542::NUMERIC,
    ALTER COLUMN pnl543 TYPE NUMERIC USING pnl543::NUMERIC,
    ALTER COLUMN pnn543 TYPE NUMERIC USING pnn543::NUMERIC,
    ALTER COLUMN pnl544 TYPE NUMERIC USING pnl544::NUMERIC,
    ALTER COLUMN pnn544 TYPE NUMERIC USING pnn544::NUMERIC,
    ALTER COLUMN pnl545 TYPE NUMERIC USING pnl545::NUMERIC,
    ALTER COLUMN pnn545 TYPE NUMERIC USING pnn545::NUMERIC,
    ALTER COLUMN pnl547 TYPE NUMERIC USING pnl547::NUMERIC,
    ALTER COLUMN pnn547 TYPE NUMERIC USING pnn547::NUMERIC,
    ALTER COLUMN pnl552 TYPE NUMERIC USING pnl552::NUMERIC,
    ALTER COLUMN pnn552 TYPE NUMERIC USING pnn552::NUMERIC,
    ALTER COLUMN pnl553 TYPE NUMERIC USING pnl553::NUMERIC,
    ALTER COLUMN pnn553 TYPE NUMERIC USING pnn553::NUMERIC,
    ALTER COLUMN pnl554 TYPE NUMERIC USING pnl554::NUMERIC,
    ALTER COLUMN pnn554 TYPE NUMERIC USING pnn554::NUMERIC,
    ALTER COLUMN pnl555 TYPE NUMERIC USING pnl555::NUMERIC,
    ALTER COLUMN pnn555 TYPE NUMERIC USING pnn555::NUMERIC,
    ALTER COLUMN pnl556 TYPE NUMERIC USING pnl556::NUMERIC,
    ALTER COLUMN pnn556 TYPE NUMERIC USING pnn556::NUMERIC,
    ALTER COLUMN pnl557 TYPE NUMERIC USING pnl557::NUMERIC,
    ALTER COLUMN pnn557 TYPE NUMERIC USING pnn557::NUMERIC,
    ALTER COLUMN pnl559 TYPE NUMERIC USING pnl559::NUMERIC,
    ALTER COLUMN pnn559 TYPE NUMERIC USING pnn559::NUMERIC,
    ALTER COLUMN pnl560 TYPE NUMERIC USING pnl560::NUMERIC,
    ALTER COLUMN pnn560 TYPE NUMERIC USING pnn560::NUMERIC,
    ALTER COLUMN pnl561 TYPE NUMERIC USING pnl561::NUMERIC,
    ALTER COLUMN pnn561 TYPE NUMERIC USING pnn561::NUMERIC,
    ALTER COLUMN pnl562 TYPE NUMERIC USING pnl562::NUMERIC,
    ALTER COLUMN pnn562 TYPE NUMERIC USING pnn562::NUMERIC,
    ALTER COLUMN pnl563 TYPE NUMERIC USING pnl563::NUMERIC,
    ALTER COLUMN pnn563 TYPE NUMERIC USING pnn563::NUMERIC,
    ALTER COLUMN pnl564 TYPE NUMERIC USING pnl564::NUMERIC,
    ALTER COLUMN pnn564 TYPE NUMERIC USING pnn564::NUMERIC,
    ALTER COLUMN pnl565 TYPE NUMERIC USING pnl565::NUMERIC,
    ALTER COLUMN pnn565 TYPE NUMERIC USING pnn565::NUMERIC,
    ALTER COLUMN pnl566 TYPE NUMERIC USING pnl566::NUMERIC,
    ALTER COLUMN pnn566 TYPE NUMERIC USING pnn566::NUMERIC,
    ALTER COLUMN pnl567 TYPE NUMERIC USING pnl567::NUMERIC,
    ALTER COLUMN pnn567 TYPE NUMERIC USING pnn567::NUMERIC,
    ALTER COLUMN pnl568 TYPE NUMERIC USING pnl568::NUMERIC,
    ALTER COLUMN pnn568 TYPE NUMERIC USING pnn568::NUMERIC,
    ALTER COLUMN pnl569 TYPE NUMERIC USING pnl569::NUMERIC,
    ALTER COLUMN pnn569 TYPE NUMERIC USING pnn569::NUMERIC,
    ALTER COLUMN pnl570 TYPE NUMERIC USING pnl570::NUMERIC,
    ALTER COLUMN pnn570 TYPE NUMERIC USING pnn570::NUMERIC,
    ALTER COLUMN pnl571 TYPE NUMERIC USING pnl571::NUMERIC,
    ALTER COLUMN pnn571 TYPE NUMERIC USING pnn571::NUMERIC,
    ALTER COLUMN pnl573 TYPE NUMERIC USING pnl573::NUMERIC,
    ALTER COLUMN pnn573 TYPE NUMERIC USING pnn573::NUMERIC,
    ALTER COLUMN pnl574 TYPE NUMERIC USING pnl574::NUMERIC,
    ALTER COLUMN pnn574 TYPE NUMERIC USING pnn574::NUMERIC,
    ALTER COLUMN pnl575 TYPE NUMERIC USING pnl575::NUMERIC,
    ALTER COLUMN pnn575 TYPE NUMERIC USING pnn575::NUMERIC,
    ALTER COLUMN pnl577 TYPE NUMERIC USING pnl577::NUMERIC,
    ALTER COLUMN pnn577 TYPE NUMERIC USING pnn577::NUMERIC,
    ALTER COLUMN pnl579 TYPE NUMERIC USING pnl579::NUMERIC,
    ALTER COLUMN pnn579 TYPE NUMERIC USING pnn579::NUMERIC,
    ALTER COLUMN pnl580 TYPE NUMERIC USING pnl580::NUMERIC,
    ALTER COLUMN pnn580 TYPE NUMERIC USING pnn580::NUMERIC,
    ALTER COLUMN pnl581 TYPE NUMERIC USING pnl581::NUMERIC,
    ALTER COLUMN pnn581 TYPE NUMERIC USING pnn581::NUMERIC,
    ALTER COLUMN pnl582 TYPE NUMERIC USING pnl582::NUMERIC,
    ALTER COLUMN pnn582 TYPE NUMERIC USING pnn582::NUMERIC,
    ALTER COLUMN pnl584 TYPE NUMERIC USING pnl584::NUMERIC,
    ALTER COLUMN pnn584 TYPE NUMERIC USING pnn584::NUMERIC,
    ALTER COLUMN pnl585 TYPE NUMERIC USING pnl585::NUMERIC,
    ALTER COLUMN pnn585 TYPE NUMERIC USING pnn585::NUMERIC;
--@block 
alter TABLE agregateds
ALTER COLUMN c19 TYPE NUMERIC USING c19::NUMERIC,
    ALTER COLUMN c20 TYPE NUMERIC USING c20::NUMERIC,
    ALTER COLUMN c21 TYPE NUMERIC USING c21::NUMERIC,
    ALTER COLUMN c22 TYPE NUMERIC USING c22::NUMERIC,
    ALTER COLUMN c23 TYPE NUMERIC USING c23::NUMERIC,
    ALTER COLUMN c24 TYPE NUMERIC USING c24::NUMERIC,
    ALTER COLUMN c25 TYPE NUMERIC USING c25::NUMERIC,
    ALTER COLUMN c26 TYPE NUMERIC USING c26::NUMERIC,
    ALTER COLUMN c27 TYPE NUMERIC USING c27::NUMERIC,
    ALTER COLUMN c28h TYPE NUMERIC USING c28h::NUMERIC,
    ALTER COLUMN c28f TYPE NUMERIC USING c28f::NUMERIC,
    ALTER COLUMN c29h TYPE NUMERIC USING c29h::NUMERIC,
    ALTER COLUMN c29f TYPE NUMERIC USING c29f::NUMERIC,
    ALTER COLUMN c30h TYPE NUMERIC USING c30h::NUMERIC,
    ALTER COLUMN c30f TYPE NUMERIC USING c30f::NUMERIC,
    ALTER COLUMN c31h TYPE NUMERIC USING c31h::NUMERIC,
    ALTER COLUMN c31f TYPE NUMERIC USING c31f::NUMERIC,
    ALTER COLUMN c32h TYPE NUMERIC USING c32h::NUMERIC,
    ALTER COLUMN c32f TYPE NUMERIC USING c32f::NUMERIC,
    ALTER COLUMN c33h TYPE NUMERIC USING c33h::NUMERIC,
    ALTER COLUMN c33f TYPE NUMERIC USING c33f::NUMERIC,
    ALTER COLUMN c34h TYPE NUMERIC USING c34h::NUMERIC,
    ALTER COLUMN c34f TYPE NUMERIC USING c34f::NUMERIC,
    ALTER COLUMN c35h TYPE NUMERIC USING c35h::NUMERIC,
    ALTER COLUMN c35f TYPE NUMERIC USING c35f::NUMERIC,
    ALTER COLUMN c36h TYPE NUMERIC USING c36h::NUMERIC,
    ALTER COLUMN c36f TYPE NUMERIC USING c36f::NUMERIC,
    ALTER COLUMN c37h TYPE NUMERIC USING c37h::NUMERIC,
    ALTER COLUMN c37f TYPE NUMERIC USING c37f::NUMERIC,
    ALTER COLUMN c38h TYPE NUMERIC USING c38h::NUMERIC,
    ALTER COLUMN c38f TYPE NUMERIC USING c38f::NUMERIC,
    ALTER COLUMN c39 TYPE NUMERIC USING c39::NUMERIC,
    ALTER COLUMN c40 TYPE NUMERIC USING c40::NUMERIC,
    ALTER COLUMN c41a TYPE NUMERIC USING c41a::NUMERIC,
    ALTER COLUMN c41b TYPE NUMERIC USING c41b::NUMERIC,
    ALTER COLUMN c42a TYPE NUMERIC USING c42a::NUMERIC,
    ALTER COLUMN c42b TYPE NUMERIC USING c42b::NUMERIC,
    ALTER COLUMN c43a TYPE NUMERIC USING c43a::NUMERIC,
    ALTER COLUMN c43b TYPE NUMERIC USING c43b::NUMERIC,
    ALTER COLUMN c44a TYPE NUMERIC USING c44a::NUMERIC,
    ALTER COLUMN c44b TYPE NUMERIC USING c44b::NUMERIC,
    ALTER COLUMN c45a TYPE NUMERIC USING c45a::NUMERIC,
    ALTER COLUMN c45b TYPE NUMERIC USING c45b::NUMERIC,
    ALTER COLUMN c45c TYPE NUMERIC USING c45c::NUMERIC,
    ALTER COLUMN c46a TYPE NUMERIC USING c46a::NUMERIC,
    ALTER COLUMN c46b TYPE NUMERIC USING c46b::NUMERIC,
    ALTER COLUMN c47a TYPE NUMERIC USING c47a::NUMERIC,
    ALTER COLUMN c47b TYPE NUMERIC USING c47b::NUMERIC,
    ALTER COLUMN c48 TYPE NUMERIC USING c48::NUMERIC,
    ALTER COLUMN c49 TYPE NUMERIC USING c49::NUMERIC;
--@block
SELECT sum(hh_f) as Number_Of_Fishery_Household,
    (sum(hh_f)::NUMERIC / sum(hh_sno)::NUMERIC)::NUMERIC * 100 as Percentage
from agregateds;
--@block
SELECT sum(hh_sno)::NUMERIC
from agregateds;
--@block Household head Information 
SELECT sum(edu) as no_education,
    (
        sum(edu1) + sum(edu2) + sum(edu3) + sum(edu4) + sum(edu5)
    ) as class_I_V,
    (sum(edu6) + sum(edu7) + sum(edu8) + sum(edu9)) as class_VI_IX,
    sum(edu10) as Scc_Passed,
    sum(edu12) as Hsc_Passed,
    sum(edu15) as Degree_Passed,
    sum(edu18) as Master_Passed,
    (
        sum(edu) + sum(edu1) + sum(edu2) + sum(edu3) + sum(edu4) + sum(edu5) + sum(edu6) + sum(edu7) + sum(edu8) + sum(edu9) + sum(edu10) + sum(edu12) + sum(edu15) + sum(edu18)
    ) as Total_Education,
    sum(occ) as Agriculture,
    sum(occ2) as Industry,
    sum(occ3) as Service,
    sum(occ4) as Business,
    sum(occ5) as Other,
    (
        sum(occ) + sum(occ2) + sum(occ3) + sum(occ4) + sum(occ5)
    ) as Total_Occupation,
    sum(c01m) as Household_Member_Male,
    sum(c01f) as Household_Member_Female,
    sum(c01h) as Household_Member_Hijra,
    (sum(c01m) + sum(c01f) + sum(c01h)) as Household_Member_Total,
    (sum(c02m) + sum(c03m)) as Household_Worker_Male,
    (sum(c02f) + sum(c03f)) as Household_Worker_Female,
    (sum(c02h) + sum(c03h)) as Household_Worker_Hijra,
    (
        sum(c02m) + sum(c03m) + sum(c02f) + sum(c03f) + sum(c02h) + sum(c03h)
    ) as Household_Worker_Total,
    sum(c02m) as Household_Worker_10_14_Male,
    sum(c02f) as Household_Worker_10_14_Female,
    sum(c02h) as Household_Worker_10_14_Hijra,
    (sum(c02m) + sum(c02f) + sum(c02h)) as Household_Worker_10_14_Total,
    sum(c03m) as Household_Worker_15_Plus_Male,
    sum(c03f) as Household_Worker_15_Plus_Female,
    sum(c03h) as Household_Worker_15_Plus_Hijra,
    (sum(c03m) + sum(c03f) + sum(c03h)) as Household_Worker_15_Plus_Total
FROM agregateds;
--@block
select geocode,
    rmo
from agregateds
where c13 = 0;
--@block
SELECT sum(occ) as Agriculture,
    sum(occ2) as Industry,
    sum(occ3) as Service,
    sum(occ4) as Business,
    sum(occ5) as Others,
    (
        sum(occ) + sum(occ2) + sum(occ3) + sum(occ4) + sum(occ5)
    ) as Total
FROM agregateds;
--@block
SELECT distinct ("union" || ' - ' || name_union) as un
FROM "geo_codes" AS "geo_codes"
WHERE (("union" || ' - ' || name_union) like '%%%')
ORDER BY "geo_codes";
--@block
SELECT (
        SELECT count(hh_sno)
        FROM agregateds
        WHERE c04 > 0
            AND subpath(geocode, 0, %d) = ?
    ) AS number_of_reporting_holdings,
    (
        SELECT count(hh_sno)
        FROM agregateds
        WHERE c18 >= 0.05
            AND C04 > 0
            AND subpath(geocode, 0, %d) = ?
    ) AS number_of_farm_holdings,
    (
        SELECT sum(c04)
        FROM agregateds
        WHERE subpath(geocode, 0, %d) = ?
    ) AS total_area_of_own_land,
    (
        SELECT sum(c18)
        FROM agregateds
        WHERE c18 >= 0.05
            AND c04 > 0
            AND subpath(geocode, 0, %d) = ?
    ) AS total_farm_holding_areas;
--@block
update geo_codes
set name_division = 'CHATTOGRAM DIVISION'
where name_division = 'CHITTAGONG DIVISION';
--@block
select distinct(pnn560)
from agregateds;
--@block
select SUM(c02m + c02f + c02h + c03m + c03f + c03h)::NUMERIC / SUM(hh_sno)::NUMERIC
from aggregates;
--@block
SELECT SUM(c02m + c02f + c02h + c03m + c03f + c03h)::NUMERIC / SUM(hh_sno)::NUMERIC as data,
    rmo
FROM aggregates
where subpath(geocode, 0, 0) = ''
    AND true = true
GROUP BY rmo
UNION
SELECT SUM(c02m + c02f + c02h + c03m + c03f + c03h)::NUMERIC / SUM(hh_sno)::NUMERIC as data,
    -1 as rmo
from aggregates;